name: tig_ep_bluetooth
description: bluetooth package for ios and android.
version: 0.0.12
homepage: http://git.myt11.com/nian.liu/tig_ep_bluetooth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0
  tig_ep_utils: ^0.0.5
  tig_bluetooth_basic: ^0.0.6
  blue_thermal_printer: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
